.. admonition:: Actividad S01-A01. Inventar un robot
   :class: note

   Estamos pensando en crear un robot fijándonos en la `hormiguita de
   fuego`_  (¿santanilla?).

   #. ¿Cuales serían sus sensores? ¿De dónde obtiene la información de lo que la rodea?
   #. ¿Cuales serían sus acciones, su forma de actuar? ¿Cómo se mueve?
   #. ¿Podrías hacer un diagrama sencillo de este robot? **En papel**.

      
.. _`hormiguita de fuego`: https://es.wikipedia.org/wiki/Wasmannia_auropunctata




	      

