.. admonition:: Actividad S01-A02. Sobre robots
   :class: note

   A continuación se muestran 5 robots concretos, sobre los que te haré 3 preguntas.

   1. Robot 1

      .. image:: /_static/imags/robot-1.webp
	 :width: 500px

   2. Robot 2

      .. image:: /_static/imags/robot-2.webp
	 :width: 500px
	      
   3. Robot 3

      .. image:: /_static/imags/robot-3.webp
	 :width: 500px
	      
   4. Robot 4

      .. image:: /_static/imags/robot-4.webp
	 :width: 500px
	      
   5. Robot 5

      .. image:: /_static/imags/robot-5.webp
	 :width: 500px

   Puedes debatir con tu grupo de trabajo en base a las siguientes
   preguntas. 

   #. ¿Qué tipo de robot crees que es cada uno?
   #. ¿Qué tipo de sensores crees que tiene?
   #. ¿Qué tipo de actuadores crees que tiene?

