.. admonition:: Actividad S02-A01. Visita Virtual a ORL
   :class: note

   ORL tiene una `visita virtual muy sencilla`_ , que te permite:
   
   #. Ver cómo usar los bloques y usar el servicio web.
   #. Crear un programa sencillo conectando bloques.
   #. Ejecutar el programa en el simulador.

   .. image:: /_static/imags/orl-visita.webp
      :width: 100%
      
   Probablemente este sencillo ejercicio llega para comenzar a programar.

	      
.. _`visita virtual muy sencilla`: https://lab.open-roberta.org/
