.. admonition:: Actividad S02-A03. Configurar un robot EV3
   :class: note

   Vamos a **configurar un robot Lego EV3** con unos requisitos
   específicos para aprender a usar el panel de configuración de
   ORL. Recuerda que cada robot, tendrá su panel de configuración
   porque tiene características diferentes.

   Esta actividad consiste en configurarlo con **los siguientes requisitos**:

   #. Hemos construido un robot con ruedas de 8 cm de diámetro y con una distancia entre ruedas de 25 cm
   #. Necesitamos obtener información del entorno con sensores para detectar contacto, color, temperatura y obstáculos
   #. Necesitamos dos motores grandes (B y C), B en el lado izquierdo y C en el lado derecho
   #. Además vamos a incorporar un motor mediano en en el puerto Motor A y un consumidor de potencia (dispositivo especial que consume energía) en el Motor D.

   .. dropdown:: Solución
      :color: info
      :animate: fade-in
		
      El resultado de la configuracion se muestra en la siguiente imagen:

      .. image:: /_static/imags/configuracion-base.webp

   
