.. admonition:: Actividad S02-A02. Programa Hola Mundo
   :class: note

   Una de las primeras tareas a la hora de aprender un lenguaje de
   programación es hacer el `programa hola mundo`_ .

   En este caso se trata de realizar el programa hola mundo en un
   robot EV3. Lo seleccionas y usas el bloque SAY ("hablar", en el menú
   acciones)

   .. dropdown:: Solución
      :color: info
      :animate: fade-in
	   
      .. image:: /_static/imags/hola-mundo.webp
	 :width: 100%
      

.. _`programa hola mundo`: https://es.wikipedia.org/wiki/Hola_mundo
