.. admonition:: Actividad S04-A01. Crear un mundo simulado
   :class: note

   En esta actividad tendrás que **crear el mundo simulado que se
   muestra** a continuación. La imagen de fondo (escenario) es uno de
   los predeterminados de ORL para el robot EV3 (tendrás que seleccionar esa escena).

   .. image:: /_static/imags/crear-mundo.webp
      :width: 100%
   
   .. dropdown:: Solución
      :color: info
      :animate: fade-in
		
      La creación del mundo implica jugar con el menú superior,
      dentro del simulador:

      #. Seleccionar un escenario vacío, sin imagen de fondo.
      #. Colocar varios obstáculos (tres círculos y un cuadrado)
      #. Colocar dos zonas de color rojo (cuadrados rojos)
      #. Colocar unas líneas gruesas negras (he usado cuadrados
	 disminuyendo su área, es aquí donde tendría sentido una
	 imagen de fondo)

      Es una actividad creativa, que puede ser de utilidad para los estudiantes.

      

   
